### ISSUE TITLE
Der Kack Timer geht net

### ISSUE THREAD

**Issue by LenMPorath** [MaRcR11/cs21-2-schedule#104]
Ich wollte gerade nachschauen wann wir vom Kevin endlich frei haben, und dann sehe ich das:
![image](https://user-images.githubusercontent.com/125283275/220390839-887d5d25-dfa6-420d-95fa-731e7b8cc263.png)

WTF

FIXT DIE KAGGE

**Comment by MaRcR11** [comment]
I think it should now be fixed with: 
```
app.set("trust proxy", 1)
```

 and I am referring to https://expressjs.com/en/guide/behind-proxies.html
