### ISSUE TITLE
Add DB to store subjects and its colors

### ISSUE THREAD

**Issue by MaRcR11** [MaRcR11/cs21-2-schedule#22]
If DB is created, develop code for checking new subjects from crawled data and add randomly generated colors

**Comment by MaRcR11** [comment]
is it legal? ;)

**Comment by Si-Ni** [comment]
> is it legal? ;)

Should be... if we don't save the data but only the subject with its color

**Comment by MaRcR11** [comment]
yeah shouldn't be a problem, but I thought about the following: almost all of the data can not only be obtained exclusively from the api, such as the subject names, which could be an argument for the fact that there is no problem.. but you could always justify it like this, in the end it is more the path the data takes that counts

**Comment by MaRcR11** [comment]
we will store it client side manually ;)
