### ISSUE TITLE
create url connection to campus dual login and get user hash with that request

### ISSUE THREAD

**Issue by MaRcR11** [MaRcR11/cs21-2-schedule#52]

**Comment by MaRcR11** [comment]
if you are able to do that, you can create user specified data (one unique schedule for every single user)


for every login-data you have to redirect (in background) that login over campus dual and try to get the hash of the specific user.

**Comment by greybaron** [comment]
The downside to that approach is:
- it requires sending individual passwords to this server in plain text; requiring trust that it is being handled securely, and not being stored
- even if that is guaranteed, the server has to store the hashes. Those can easily be abused to collect grades/exam stats/credit points.

I don't think user-specific data is worth the effort, security implications and inherent downsides
