### ISSUE TITLE
add appearance switch (dark/light mode)

### ISSUE THREAD

**Issue by MaRcR11** [MaRcR11/cs21-2-schedule#62]

**Comment by MaRcR11** [comment]
![image](https://user-images.githubusercontent.com/91952791/214951233-bdd85ca5-f7a3-4ceb-9871-95fb5c846295.png)

- should be look similar to this
- default should be still dark mode

**Comment by greybaron** [comment]
I think the default shouldn't be dark mode but rather the theme that the browser requests (usually the color scheme of the user OS)
